import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-elev": "var(--bg-elev)",
        "bg-elev-2": "var(--bg-elev-2)",
        ink: "var(--ink)",
        "ink-soft": "var(--ink-soft)",
        muted: "var(--muted)",
        "muted-soft": "var(--muted-soft)",
        line: "var(--line)",
        accent: "var(--accent)",
        "accent-warm": "var(--accent-warm)",
        "inverse-on-surface": "#322f35",
        "surface-tint": "#cfbcff",
        "inverse-primary": "#6750a4",
        "tertiary-fixed": "#ffdf93",
        "tertiary-container": "#c9a74d",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        background: "#ffffff",
        "surface-container-high": "#e4e4e7",
        secondary: "#d8b4fe",
        "surface-variant": "#f4f4f5",
        "on-surface": "#000000",
        "primary-container": "#d8b4fe",
        "on-background": "#000000",
        "primary-fixed-dim": "#cfbcff",
        "surface-container-low": "#fafafa",
        "on-secondary-fixed-variant": "#4b4263",
        "primary-fixed": "#e9ddff",
        "on-secondary-container": "#bfb2da",
        "on-primary-container": "#e0d2ff",
        "on-surface-variant": "#52525b",
        "on-secondary": "#342b4b",
        "on-primary": "#ffffff",
        "surface-bright": "#ffffff",
        tertiary: "#fde047",
        surface: "#ffffff",
        "on-tertiary": "#3e2e00",
        "secondary-fixed-dim": "#cdc0e9",
        primary: "#000000",
        "secondary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#e7c365",
        "surface-container": "#f4f4f5",
        "error-container": "#93000a",
        "on-primary-fixed": "#22005d",
        "on-error": "#ffffff",
        "surface-container-highest": "#d4d4d8",
        "on-tertiary-fixed-variant": "#594400",
        "surface-dim": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "rgba(0,0,0,0.1)",
        "on-secondary-fixed": "#1f1635",
        "on-tertiary-fixed": "#241a00",
        outline: "rgba(0,0,0,0.2)"
      },
      fontFamily: {
        serif: ["'Instrument Serif'", "Times New Roman", "serif"],
        sans: ["'Inter Tight'", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        display: ["'Bodoni Moda'", "'Playfair Display'", "Georgia", "serif"],
        body: ["'Manrope'", "-apple-system", "sans-serif"],
        h1: ["'Inter Tight'", "sans-serif"],
        "h1-mobile": ["'Inter Tight'", "sans-serif"],
        "mono-label": ["'JetBrains Mono'", "monospace"],
        h2: ["'Inter Tight'", "sans-serif"],
        h3: ["'Inter Tight'", "sans-serif"],
        "body-lg": ["'Manrope'", "sans-serif"],
        "body-md": ["'Manrope'", "sans-serif"],
        "mono-data": ["'JetBrains Mono'", "monospace"],
      },
      letterSpacing: {
        tightest: "-0.035em",
      },
      spacing: {
        xl: "80px",
        "container-max": "1440px",
        lg: "48px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        base: "8px",
        gutter: "24px"
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "mono-label": ["13px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "1.4", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
